<?php
include('Excepciones.php');

$number = 0;

try {
    echo 'Number: ' . ExcepcionPropiaClase::testNumber($number);
} catch (Exception $e) {
    echo 'ExcepciÃ³n capturada: ', $e->getMessage(), "\n";
}
